# Generated by Django 4.2.1 on 2025-05-10 20:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('task_id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('To Do', 'Todo'), ('In Progress', 'In Progress'), ('Blocked', 'Blocked'), ('In Review', 'In Review'), ('Completed', 'Completed')], default='To Do', max_length=20)),
                ('estimated_effort', models.FloatField(blank=True, null=True)),
                ('actual_effort', models.FloatField(blank=True, null=True)),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('completion_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-creation_date'],
            },
        ),
    ]
